name: PlayerBountiesPlus
version: '${project.version}'
main: com.tcoded.playerbountiesplus.PlayerBountiesPlus
api-version: 1.13
authors: [ TechnicallyCoded ]
description: Claim bounties only if you are not on the same clan
website: https://tcoded.com
folia-supported: true

depend:
  - Vault
softdepend:
  - ClansLite
  - Parties
  - BetterTeams
  - SimpleClans
  - Towny

commands:
  bounty:
    permission: playerbountiesplus.command.bounty
    aliases: [bounties, prime, primes]
  playerbountiesplusadmin:
    permission: playerbountiesplus.command.admin
    aliases: [playerbountiesplus, pbpa, pbp]

permissions:
  playerbountiesplus.command.bounty:
    default: true
  playerbountiesplus.command.admin:
    default: op
    children:
      playerbountiesplus.command.admin.version: {}
      playerbountiesplus.command.admin.reload: {}
      playerbountiesplus.command.admin.bounty.set: {}
      playerbountiesplus.command.admin.bounty.add: {}
      playerbountiesplus.command.admin.bounty.remove: {}
      playerbountiesplus.command.admin.bounty.delete: {}
  playerbountiesplus.command.bounty.set:
    default: true
  playerbountiesplus.event.claim:
    default: true
