name: PlayerBountiesPlus
version: '${project.version}'
main: com.tcoded.playerbountiesplus.PlayerBountiesPlus
api-version: 1.13
authors: [ TechnicallyCoded ]
description: Claim bounties only if you are not on the same clan
website: https://tcoded.com
folia-supported: true

depend:
  - Vault
softdepend:
  - ClansLite
  - Parties
  - BetterTeams
  - SimpleClans
  - Towny

commands:
  bounty:
    permission: playerbountiesplus.command.bounty
    aliases: [bounties, prime, primes]
  playerbountiesplusadmin:
    aliases: [playerbountiesplus, pbpa, pbp]

permissions:
  playerbountiesplus.command.bounty:
    default: true
  playerbountiesplus.command.playerbountiesplus:
    children:
      playerbountiesplus.command.playerbountiesplus.version:
        default: true
      playerbountiesplus.command.playerbountiesplus.reload:
        default: op
      playerbountiesplus.command.playerbountiesplus.admin.set:
        default: op
      playerbountiesplus.command.playerbountiesplus.admin.add:
        default: op
      playerbountiesplus.command.playerbountiesplus.admin.remove:
        default: op
      playerbountiesplus.command.playerbountiesplus.admin.delete:
        default: op
